apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    component: postgres
spec:
  replicas: 1 # Only one DB instance in this setup
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432 # PostgreSQL default port
          env: # Using Kubernetes secrets for secure credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-flask-app
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-flask-app
                  key: DB_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets-flask-app
                  key: DB_NAME
          volumeMounts: # Persist database storage
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes: # List of availables volume for this development
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc # PVC for DB persistence
      nodeSelector:
        role: db # Ensures DB runs on specific nodes