apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: gp2 # for aws eks dynamic store ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi