apiVersion: apps/v1
kind: Deployment
metadata:
	name: flask-app-deployment
  labels:
    component: flask-app
spec:
  replicas: 3
  selector: # tell what is the select for this deployment for the pods (key: value)
    matchLabels:
      component: flask-app
  template: # configure what template for your containers
    metadata:
      labels:
        component: flask-app
    specs:
      containers:
        - name: flask-app
          image: joseriosve/flask_app_distributed
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef: # import all your secret to this app
                name: secrets-flask-app

          # It starts gunicorn, binding it to port 8000.
          #command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "app:create_app()"]
          # Optionally, you can add environment variables, resource limits, and probes.
          # env:
          #   - name: FLASK_ENV
          #     value: production