apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    component: flask-app
spec:
  replicas: 2
  selector: # tell what is the select for this deployment for the pods (key: value)
    matchLabels:
      component: flask-app
  template: # configure what template for your containers
    metadata:
      labels:
        component: flask-app
    spec:
      nodeSelector: # to schedule pods on nodes with this label
        role: app
      containers:
      - name: flask-app
        image: joseriosve/flask_app_distributed:v2
        ports:
        - containerPort: 8000
        envFrom: # import all your secret to this app
        - secretRef:
            name: secrets-flask-app
        command: # this command will run Gunicorn with 3 workers, binding on port 8000, and execute the "create_app()" callable from your "app" module
        - "gunicorn"
        - "--workers"
        - "3"
        - "--bind"
        - "0.0.0.0:8000"
        - "app:create_app()"