apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: default
spec:
  ingressClassName: nginx # required by new versions of k8s
  rules:
    - host: abe9c407b6e5b4a5a82545fd8f24ede7-271592874.us-east-1.elb.amazonaws.com  # external ip load balancer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app-cluster-ip-service
                port:
                  number: 80