apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: default
spec:
  ingressClassName: nginx # required by new versions of k8s
  rules:
    - host: a555b63ab910f4f10ab8829f833d739e-1644496394.us-east-1.elb.amazonaws.com # external ip load balancer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app-cluster-ip-service
                port:
                  number: 80