apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: default
spec:
  ingressClassName: nginx # required by new versions of k8s
  rules:
    - host: a60c17b7c194e47ba9800173d5c1d7cb-1226030644.us-east-1.elb.amazonaws.com  # external ip load balancer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app-cluster-ip-service
                port:
                  number: 80