apiVersion: batch/v1
kind: Job
metadata:
  name: flask-db-migration
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migration-container
          image: joseriosve/flask_app_distributed:v2
          command: ["sh", "-c", "
            echo 'Running database migrations...';
            flask db upgrade"]
          envFrom: # Load ALL secrets for environment variables
            - secretRef:
                name: secrets-flask-app
      restartPolicy: OnFailure # Ensures the job runs only once