apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: flask-db
  namespace: default
spec:
  teamId: "myteamDemo"
  # 1 primary + 2 replicas
  numberOfInstances: 3
  postgresql:
    version: "14"
  # Persistent volume claim for each pod
  volume:
    size: 5Gi
    storageClass: gp2
  # Users and roles
  users:
    postgres:
      - superuser
      - createdb
  # Databases: <db-name>: <owner>
  databases:
    flask_db_1: postgres
  # Tell the operator how to initially create your db (can you install here the extension like postgis)
  preparedDatabases:
    flask_db_1: {}
