# This role is need to tell patroni to use the Kubernetes api to use as Distributed Configuration Store (DCS)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni
  namespace: postgres-patroni
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: postgres-patroni
  name: patroni-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "services", "configmaps"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni-rolebinding
  namespace: postgres-patroni
subjects:
  - kind: ServiceAccount
    name: patroni
roleRef:
  kind: Role
  name: patroni-role
  apiGroup: rbac.authorization.k8s.io