"""Make user.password column nullable

Revision ID: 3611e8c7db5b
Revises: 388058e5ac6e
Create Date: 2025-05-15 19:29:03.400912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3611e8c7db5b'
down_revision = '388058e5ac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema='admin') as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('author_book', schema='authors') as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_book', schema='authors') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('user', schema='admin') as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
