"""empty message

Revision ID: 388058e5ac6e
Revises: 664a2d633d9e
Create Date: 2025-05-15 19:14:18.855884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388058e5ac6e'
down_revision = '664a2d633d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    with op.batch_alter_table('token_blocklist', schema='admin') as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('role', sa.Enum('guest', 'admin', 'superadmin', name='userroleenum'), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='admin'
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='authors'
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='authors'
    )
    op.create_table('author_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['authors.book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='authors'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_book', schema='authors')
    op.drop_table('book', schema='authors')
    op.drop_table('author', schema='authors')
    op.drop_table('user', schema='admin')
    with op.batch_alter_table('token_blocklist', schema='admin') as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_token_blocklist_jti'))

    op.drop_table('token_blocklist', schema='admin')
    # ### end Alembic commands ###
