"""empty message

Revision ID: dcf460af1118
Revises: 3611e8c7db5b
Create Date: 2025-05-16 12:20:05.146065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf460af1118'
down_revision = '3611e8c7db5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema='authors') as batch_op:
        batch_op.add_column(sa.Column('slug_book', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['slug_book'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema='authors') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug_book')

    # ### end Alembic commands ###
